# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]  
        include:
        - os: ubuntu-latest
        - os1: windows-latest

    steps:
      - name: pull nginx image
        env:
          os: ${{ matrix.os }}
        run: docker pull nginx   
        
      - name: pull win iis image
        env:
          os1: ${{ matrix.os1 }}
        run: docker pull mcr.microsoft.com/windows/servercore

  
