# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_web_app1:
    name: Build WebApp1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull nginx image
      run: |
        docker pull nginx   
      
  
  build_web_app2:
    name: Build WebApp2
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2 
    - name: pull windows image
      run: |
        docker pull mcr.microsoft.com/windows/servercore:ltsc2019



  
