# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # TODO: update to cluster name
  GKE_ZONE: us-central1-c # TODO: update to cluster zone
  DEPLOYMENT_NAME: mydep # TODO: update to deployment name
  IMAGE: gke-nginxapp-image10
  TAG: 1.0.0


jobs:
  build_web_app1:
    name: Build WebApp1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull nginx image
      run: |
        docker pull nginx   
      
  
  build_web_app2:
    name: Build WebApp2
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2 
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        
        
     # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
  
    # Build the Docker image
    - name: Build
      run: |-
       # docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
          
     # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"



  
